name: test-bt_ocean-32

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      JAX_ENABLE_X64: False
      KERAS_BACKEND: jax
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: bt_ocean
      - name: Install dependencies
        run: |
          python3 -m venv bt_ocean_venv
          . bt_ocean_venv/bin/activate
          python3 -m pip install flake8 h5py jax[cpu] keras matplotlib numpy pytest pytest-timeout pytest-xdist ruff sympy zarr
      - name: Lint
        run: |
          . bt_ocean_venv/bin/activate
          cd bt_ocean
          flake8
          ruff check
      - name: Run tests (32 bit)
        run: |
          . bt_ocean_venv/bin/activate
          cd bt_ocean
          python3 -m pytest -v -n 2 --timeout=300 --timeout-method=thread
